'use server';
/**
 * @fileOverview AI flow to generate step-by-step explanations for questions in math, programming, or web development.
 *
 * - generateStepByStepExplanation - A function that generates step-by-step explanations.
 * - GenerateStepByStepExplanationInput - The input type for the generateStepByStepExplanation function.
 * - GenerateStepByStepExplanationOutput - The return type for the generateStepByStepExplanation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateStepByStepExplanationInputSchema = z.object({
  question: z.string().describe('The question asked by the student.'),
});
export type GenerateStepByStepExplanationInput = z.infer<typeof GenerateStepByStepExplanationInputSchema>;

const GenerateStepByStepExplanationOutputSchema = z.object({
  explanation: z.string().describe('The step-by-step explanation generated by the AI.'),
});
export type GenerateStepByStepExplanationOutput = z.infer<typeof GenerateStepByStepExplanationOutputSchema>;

export async function generateStepByStepExplanation(input: GenerateStepByStepExplanationInput): Promise<GenerateStepByStepExplanationOutput> {
  return generateStepByStepExplanationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateStepByStepExplanationPrompt',
  input: {schema: GenerateStepByStepExplanationInputSchema},
  output: {schema: GenerateStepByStepExplanationOutputSchema},
  prompt: `You are an AI tutor specializing in providing step-by-step explanations for students.

  A student has asked the following question:
  {{question}}

  Provide a clear and concise step-by-step explanation to help the student understand the concept.`,
});

const generateStepByStepExplanationFlow = ai.defineFlow(
  {
    name: 'generateStepByStepExplanationFlow',
    inputSchema: GenerateStepByStepExplanationInputSchema,
    outputSchema: GenerateStepByStepExplanationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
